name: astral
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.3  # Add this line
  cupertino_icons: ^1.0.8
  rust_lib_astral:
    path: rust_builder
  flutter_rust_bridge: 2.9.0
  signals_flutter: ^6.0.2
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  window_manager: ^0.4.3
  flutter_colorpicker: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.13
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  
