name: 🛠️ 构建 Android APK

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: 🛠️ 检出代码仓库
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: 🦀 设置 Rust 工具链
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: 📦 安装系统依赖
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libc6-dev
          sudo apt-get install -y libc6-dev-armhf-cross gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf
          sudo apt-get install -y clang llvm libclang-dev
          sudo apt-get install -y libc-dev
          sudo apt-get install -y libc6-dev-i386
          sudo apt-get install -y protobuf-compiler

      - name: 🎯 配置 Rust 目标架构
        run: |
          rustup target add armv7-linux-androideabi
          rustup target add aarch64-linux-android

      - name: ☕ 设置 JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: 🤖 设置 Android SDK
        uses: android-actions/setup-android@v3
        with:
          ndk-version: '27.2.12479018'
          cmake-version: '3.18.1'

      - name: 🐦 安装 Flutter
        run: |
          git clone https://github.com/flutter/flutter.git -b stable
          echo "PATH=$GITHUB_WORKSPACE/flutter/bin:$PATH" >> $GITHUB_ENV
          source $GITHUB_ENV
          flutter --version

      - name: 📚 安装 Flutter 依赖
        run: |
          flutter pub get

  build-all:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: 🛠️ 构建全架构 APK (ALL)
        run: |
          flutter build apk --release

      - name: 📤 上传全架构 APK (ALL)
        uses: actions/upload-artifact@v4
        with:
          name: app-release-all
          path: build/app/outputs/flutter-apk/app-release.apk

  build-x86:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: 🛠️ 构建 x86 架构 APK
        run: |
          flutter build apk --release --target-platform android-x86

      - name: 📤 上传 x86 架构 APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-x86
          path: build/app/outputs/flutter-apk/app-x86-release.apk

  build-x86_64:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: 🛠️ 构建 x86_64 架构 APK
        run: |
          flutter build apk --release --target-platform android-x64

      - name: 📤 上传 x86_64 架构 APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-x86_64
          path: build/app/outputs/flutter-apk/app-x86_64-release.apk

  build-arm64-v8a:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: 🛠️ 构建 arm64-v8a 架构 APK
        run: |
          flutter build apk --release --target-platform android-arm64

      - name: 📤 上传 arm64-v8a 架构 APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-arm64-v8a
          path: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk

  build-armeabi-v7a:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: 🛠️ 构建 armeabi-v7a 架构 APK
        run: |
          flutter build apk --release --target-platform android-arm

      - name: 📤 上传 armeabi-v7a 架构 APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-armeabi-v7a
          path: build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
