name: 🛠️ Android 构建全架构 APK

on:
  workflow_call: {}  # 允许被其他工作流调用

jobs:
  build-all:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: 🛠️ 检出代码仓库
        uses: actions/checkout@v4

      - name: 🐦 设置 Flutter
        run: |
          export PATH="$HOME/flutter/bin:$PATH"
          echo "PATH: $PATH"
          which flutter
          flutter --version

      - name: 🛠️ 构建全架构 APK (ALL)
        run: |
          flutter build apk --release

      - name: 📤 上传全架构 APK (ALL)
        uses: actions/upload-artifact@v4
        with:
          name: app-release-all
          path: build/app/outputs/flutter-apk/app-release.apk
