name: 构建 Android

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          ndk-version: '27.2.12479018'
          cmake-version: '3.18.1'

      - name: Verify current directory
        run: |
          echo "Current working directory: $(pwd)"
          ls -la

      - name: Switch to Android directory
        run: |
          cd android

      - name: Install Flutter
        run: |
          echo "Cloning Flutter stable branch..."
          git clone https://github.com/flutter/flutter.git -b stable
          echo "Verifying Flutter directory..."
          ls -la $GITHUB_WORKSPACE/flutter
          echo "Adding Flutter to PATH..."
          echo "$GITHUB_WORKSPACE/flutter/bin" >> $GITHUB_PATH
          echo "PATH is: $PATH"
          echo "Testing Flutter command..."
          $GITHUB_WORKSPACE/flutter/bin/flutter --version

      - name: Install Flutter dependencies
        run: |
          echo "Fetching Flutter dependencies..."
          flutter pub get
          echo "Flutter dependencies installed."

      - name: Build Flutter APK
        run: |
          echo "Building Flutter release APK..."
          flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
