name: 构建 Android

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libc6-dev
          sudo apt-get install -y libc6-dev-armhf-cross gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf
          sudo apt-get install -y clang llvm libclang-dev

      - name: Configure Rust target
        run: |
          rustup target add armv7-linux-androideabi
          rustup target add aarch64-linux-android

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          ndk-version: '27.2.12479018'
          cmake-version: '3.18.1'

      - name: Install Flutter
        run: |
          git clone https://github.com/flutter/flutter.git -b stable
          echo "PATH=$GITHUB_WORKSPACE/flutter/bin:$PATH" >> $GITHUB_ENV
          source $GITHUB_ENV
          flutter --version

      - name: Install Flutter dependencies
        run: |
          flutter pub get

      - name: Build Rust library
        run: |
          export CC=arm-linux-gnueabihf-gcc
          export CXX=arm-linux-gnueabihf-g++
          export AR=arm-linux-gnueabihf-ar
          export RANLIB=arm-linux-gnueabihf-ranlib
          cargo build --target armv7-linux-androideabi --release

      - name: Build Flutter APK
        run: |
          flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
