name: 构建 Android

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
      # ✅ 检出代码，确保完整文件
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      # ✅ 设置 JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      # ✅ 设置 Android SDK 和 NDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          ndk-version: '27.2.12479018'
          cmake-version: '3.18.1'

      # ✅ 检查当前目录
      - name: Verify current directory
        run: |
          echo "Current working directory: $PWD"
          ls

      # ✅ 切换到 Android 目录
      - name: Switch to Android directory
        run: |
          cd android

      # ✅ 检查 Gradle Wrapper 文件
      - name: Check for Gradle Wrapper
        run: |
          if (-Not (Test-Path ".\gradlew.bat")) {
            echo "Gradle wrapper not found, installing it..."
            gradle wrapper
          }
          echo "Gradle wrapper is present."

      # ✅ 清理 Gradle 缓存
      - name: Clean Gradle Cache
        run: |
          echo "Cleaning Gradle cache..."
          .\gradlew.bat clean
          rm -rf ~/.gradle/caches
          echo "Gradle cache cleaned."

      # ✅ 安装 Flutter
      - name: Install Flutter
        run: |
          echo "Cloning Flutter stable branch..."
          git clone https://github.com/flutter/flutter.git -b stable
          echo "Adding Flutter to PATH..."
          echo "$env:GITHUB_WORKSPACE\flutter\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "Flutter installation completed."

      # ✅ 安装 Flutter 依赖
      - name: Install Flutter dependencies
        run: |
          echo "Fetching Flutter dependencies..."
          flutter pub get
          echo "Flutter dependencies installed."

      # ✅ 构建 Flutter
