name: 🚀 发布

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.0.0)'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    # 调整 GITHUB_TOKEN 的权限
    permissions:
      contents: write  # 允许写入仓库内容（上传文件）

    steps:
          - uses: actions/checkout@v4
    
          - name: 📦 下载 x86_64 架构 APK
            uses: actions/download-artifact@v4
            with:
              name: app-release-arm64-v8a
              path: ./downloaded-apks
    
          - name: 🖨️ 打印下载的文件
            run: ls -R ./downloaded-apks

      # 创建 GitHub Release 并上传压缩包
      # - name: Create GitHub Release
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     name: Release ${{ inputs.version }}
      #     draft: true
      #     files: ${{ github.workspace }}/release.zip
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     tag_name: ${{ inputs.version }}
