name: 🚀 发布

on:
  workflow_dispatch:
    inputs:
      base_branch:
        description: '基础分支 (例如: v0.0.0)'
        required: true
        default: 'v1.'
        type: string
      head_branch:
        description: '目标分支 (例如: main)'
        required: true
        default: 'main'
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    # 调整 GITHUB_TOKEN 的权限
    permissions:
      contents: write  # 允许写入仓库内容（上传文件）
      actions: read    # 允许读取工作流程

    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整历史记录，以便比较分支
        
      - name: 📦 下载 arm64-v8a 构件
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: "android-build-arm64.yaml"
          name: app-release-arm64-v8a
          path: ./downloaded/arm64-v8a
          search_artifacts: true
          if_no_artifact_found: warn
      - run: mv ./downloaded/arm64-v8a/* ./downloaded/arm64-v8a/app-release-arm64-v8a.apk

      - name: 📦 下载 Windows 构件
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: "windows-build.yml"
          name: release
          path: ./downloaded/windows
          search_artifacts: true
          if_no_artifact_found: warn
      
      - name: 📦 下载 WindowsSetup 构件
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: "windows-build-Setup.yml"
          name: release
          path: ./downloaded/windowsSetup
          search_artifacts: true
          if_no_artifact_found: warn

      - name: 📝 列出下载的文件
        run: |
          echo "已下载的文件列表:"
          ls -la ./downloaded
          echo "armeabi-v7a 文件:"
          ls -la ./downloaded/armeabi-v7a || echo "目录不存在"
          echo "arm64-v8a 文件:"
          ls -la ./downloaded/arm64-v8a || echo "目录不存在"
          echo "所有架构文件:"
          ls -la ./downloaded/all || echo "目录不存在"
          echo "x86_64 文件:"
          ls -la ./downloaded/x86_64 || echo "目录不存在"
          echo "Windows 文件:"
          ls -la ./downloaded/windows || echo "目录不存在"
          echo "WindowsSetup 文件:"
          ls -la./downloaded/windowsSetup || echo "目录不存在"
          
      - name: 🤖 生成分支差异提交内容
        id: generate_changelog
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE }}
        run: |
          # 获取两个分支之间的提交信息
          COMMITS=$(git log --pretty=format:"%h - %s (%an)" ${{ github.event.inputs.base_branch }}..${{ github.event.inputs.head_branch }})
          
          # 将提交信息保存到文件
          echo "$COMMITS" > commits.txt
          
          # 安装 Python 和必要的库
          pip install google-generativeai
          
          # 创建 Python 脚本生成更新日志
          cat > generate_changelog.py << EOF
          import google.generativeai as genai
          import os
          import sys
          
          try:
              api_key = os.environ.get('GOOGLE_API_KEY')
              if not api_key:
                  print("Error: GOOGLE_API_KEY environment variable not found")
                  sys.exit(1)
                  
              # 配置 API 密钥
              genai.configure(api_key=api_key)
              
              # 读取提交信息
              with open('commits.txt', 'r') as f:
                  commits = f.read()
              
              if not commits.strip():
                  print("No commits found between specified branches")
                  with open('CHANGELOG.md', 'w') as f:
                      f.write("# 更新日志\n\n无更新内容")
                  sys.exit(0)
              
              # 设置模型和生成参数
              model = genai.GenerativeModel('gemini-1.5-flash')
              prompt = f"""
              请根据以下Git提交记录生成规范的更新日志文档：

              ## 提交记录详情
              {commits}

              生成要求：
              1. 标题格式：
                 # 版本更新概要 
                 > 一句话简述本次更新要点

              2. 内容分类（请严格按照以下顺序和图标）：
                 ## 🚀 新增功能
                 - 新功能条目1
                 - 新功能条目2
                 
                 ## 🔧 问题修复
                 - 修复内容1
                 - 修复内容2
                 
                 ## 🌟 功能优化
                 - 优化内容1
                 - 优化内容2

              3. 内容要求：
                 - 每个条目使用简洁的动词开头
                 - 描述要具体且清晰
                 - 避免技术术语，使用用户友好的表述
                 - 相似改动归类合并
              
              4. 格式规范：
                 - 使用 Markdown 格式
                 - 每个分类下使用无序列表（-）
                 - 保持统一的缩进
                 - 条目间保留适当空行
              """
              # 生成更新日志
              response = model.generate_content(prompt)
              
              # 保存结果
              with open('CHANGELOG.md', 'w') as f:
                  f.write("# 更新日志\n\n")
                  f.write(response.text)
                  
          except Exception as e:
              print(f"Error: {str(e)}")
              sys.exit(1)
          EOF
          
          # 执行 Python 脚本
          python generate_changelog.py
          
          # 将更新日志内容设置为输出变量
          CHANGELOG=$(cat CHANGELOG.md)
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGELOG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          
      - name: 🚀 创建草稿发布
        uses: softprops/action-gh-release@v1
        with:
          name: 发布 ${{ github.event.inputs.head_branch }}
          tag_name: release-${{ github.run_number }}
          body: ${{ steps.generate_changelog.outputs.changelog }}
          draft: true  # 设置为草稿状态
          prerelease: true  # 标记为预发布版本
          files: |
            ./downloaded/arm64-v8a/*.apk
            ./downloaded/windowsSetup/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
