name: 🚀 发布

on:
  workflow_dispatch:
    inputs:
      base_branch:
        description: '基础分支 (例如: main)'
        required: true
        default: 'main'
        type: string
      head_branch:
        description: '目标分支 (例如: develop)'
        required: true
        default: 'develop'
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    # 调整 GITHUB_TOKEN 的权限
    permissions:
      contents: write  # 允许写入仓库内容（上传文件）
      actions: read    # 允许读取工作流程

    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整历史记录，以便比较分支
        
      - name: 📦 下载 armeabi-v7a 构件
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: "android-build-armv7.yaml"
          name: app-release-armeabi-v7a
          path: ./downloaded/armeabi-v7a
          search_artifacts: true
          if_no_artifact_found: warn
          
      # ... 其他下载步骤保持不变 ...
          
      - name: 📝 列出下载的文件
        run: |
          echo "已下载的文件列表:"
          ls -la ./downloaded
          echo "armeabi-v7a 文件:"
          ls -la ./downloaded/armeabi-v7a || echo "目录不存在"
          echo "arm64-v8a 文件:"
          ls -la ./downloaded/arm64-v8a || echo "目录不存在"
          echo "所有架构文件:"
          ls -la ./downloaded/all || echo "目录不存在"
          echo "x86_64 文件:"
          ls -la ./downloaded/x86_64 || echo "目录不存在"
          echo "Windows 文件:"
          ls -la ./downloaded/windows || echo "目录不存在"
          
      - name: 🤖 生成分支差异提交内容
        id: generate_changelog
        env:
          GOOGLE_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          # 获取两个分支之间的提交信息
          COMMITS=$(git log --pretty=format:"%h - %s (%an)" ${{ github.event.inputs.base_branch }}..${{ github.event.inputs.head_branch }})
          
          # 将提交信息保存到文件
          echo "$COMMITS" > commits.txt
          
          # 安装 Python 和必要的库
          pip install google-generativeai
          
          # 创建 Python 脚本生成更新日志
          cat > generate_changelog.py << 'EOF'
          import google.generativeai as genai
          import os
          
          # 配置 API 密钥
          genai.configure(api_key=os.environ['GOOGLE_API_KEY'])
          
          # 读取提交信息
          with open('commits.txt', 'r') as f:
              commits = f.read()
          
          # 设置模型和生成参数
          model = genai.GenerativeModel('gemini-1.5-flash')  # 修改为 Gemini 2.0 Flash
          prompt = f"""
          请根据以下Git提交记录，生成一份用户友好的更新日志。
          将内容分类为"新功能"、"改进"、"修复"等类别。
          使用简洁明了的中文描述每项变更。
          
          提交记录:
          {commits}
          """
          
          # 生成更新日志
          response = model.generate_content(prompt)
          
          # 保存结果
          with open('CHANGELOG.md', 'w') as f:
              f.write("# 更新日志\n\n")
              f.write(response.text)
          EOF
          
          # 执行 Python 脚本
          python generate_changelog.py
          
          # 将更新日志内容设置为输出变量
          CHANGELOG=$(cat CHANGELOG.md)
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGELOG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          
      - name: 🚀 创建草稿发布
        uses: softprops/action-gh-release@v1
        with:
          name: 发布 ${{ github.event.inputs.head_branch }}
          tag_name: release-${{ github.run_number }}
          body: ${{ steps.generate_changelog.outputs.changelog }}
          draft: true  # 设置为草稿状态
          prerelease: true  # 标记为预发布版本
          files: |
            ./downloaded/armeabi-v7a/*.apk
            ./downloaded/arm64-v8a/*.apk
            ./downloaded/all/*.apk
            ./downloaded/x86_64/*.apk
            ./downloaded/windows/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}