name: 🚀 发布

on:
  workflow_dispatch:
    # inputs:
    #   version:
    #     description: 'Release version (e.g., v1.0.0)'
    #     required: true
    #     type: string

jobs:
  build:
    runs-on: ubuntu-latest

    # 调整 GITHUB_TOKEN 的权限
    permissions:
      contents: write  # 允许写入仓库内容（上传文件）

    steps:
      - name: 📦 下载最新构建的 APK
        uses: actions/download-artifact@v4
        with:
          name: app-release-armeabi-v7a
          path: ./downloaded-apks
          # 移除了不支持的 workflow 和 run_id 参数
          # 使用 pattern 参数来匹配文件名
          pattern: '*.apk'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: 📝 列出下载的文件
        run: |
          echo "已下载的文件列表:"
          ls -la ./downloaded-apks
