name: 🐧 构建 Linux 应用

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'   # 当推送版本标签时触发

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    
    steps:
      - name: 🛠️ 检出代码仓库
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: 🦀 设置 Rust 工具链
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: 📦 安装系统依赖
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential ninja-build libgtk-3-dev
          sudo apt-get install -y clang cmake pkg-config libgtk-3-dev
          sudo apt-get install -y liblzma-dev libstdc++-12-dev
          sudo apt-get install -y libsecret-1-dev libjsoncpp-dev
          sudo apt-get install -y protobuf-compiler

      - name: 🐦 安装 Flutter
        run: |
          git clone https://github.com/flutter/flutter.git -b stable $HOME/flutter
          echo "$HOME/flutter/bin" >> $GITHUB_PATH
          export PATH="$HOME/flutter/bin:$PATH"
          chmod +x $HOME/flutter/bin/flutter
          flutter --version

      - name: 🎯 启用 Linux 桌面支持
        run: |
          flutter config --enable-linux-desktop

      - name: 📚 安装 Flutter 依赖
        run: |
          flutter pub get

      - name: 🛠️ 构建 Linux 应用
        run: |
          flutter build linux --release

      - name: 📦 打包应用
        run: |
          cd build/linux/x64/release/bundle
          tar -czf ../../../../../astral-linux.tar.gz *

      - name: 📤 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: linux-release
          path: astral-linux.tar.gz